// Canonical → compact transform (BUILD_PLAN.md 0.8; DATA_SPEC.md §4.4).
// Run: npm run build:compact. Writes data/generated/compounds.compact.json,
// the ONLY data file the app imports. It is build output: never hand-edited,
// gitignored, regenerated on every build, and marked "$generated": true.
//
// Fields per §4.4: id, compound, reading, chars[] {k, r, t}, cls, diff,
// changes, changeDetail, context, trap, chains[], alternates[]. Additive fields
// beyond §4.4, each derived one-to-one from a canonical field so the round-trip
// test covers them: chars[].on / .kun / .note (the character's dictionary
// readings and note), contested, contestedNote, tags, unclassifiable. The
// inspection page and the Phase 1 modes need them; the prototype's schema had
// no slot for them.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { DatasetSchema, type Entry } from "../src/data/schema";
import type { CompactEntry, CompactFile } from "../src/data/compact";

export type { CompactEntry, CompactFile } from "../src/data/compact";

const ROOT = process.cwd();
const DATA = join(ROOT, "data", "compounds.json");
export const COMPACT_PATH = join(ROOT, "data", "generated", "compounds.compact.json");

export function toCompact(e: Entry): CompactEntry {
  return {
    id: e.id,
    compound: e.compound,
    reading: e.reading,
    chars: e.characters.map((c) => ({ k: c.kanji, r: c.reading_in_compound, t: c.reading_type, on: c.on_readings, kun: c.kun_readings, note: c.reading_note })),
    cls: e.classification,
    diff: e.difficulty,
    changes: e.phonetic_changes,
    changeDetail: e.phonetic_change_detail,
    context: e.real_world_context,
    trap: e.trap_note,
    chains: e.chains,
    alternates: e.alternate_readings.map((a) => ({ reading: a.reading, cls: a.classification, status: a.status, context: a.context })),
    contested: e.contested,
    contestedNote: e.contested_note,
    tags: e.tags,
  };
}

export function loadCanonical(): { $schema_version: string; entries: Entry[] } {
  const parsed = DatasetSchema.safeParse(JSON.parse(readFileSync(DATA, "utf8")));
  if (!parsed.success) throw new Error("data/compounds.json does not conform to the schema; run npm run validate");
  return parsed.data;
}

export function buildCompact(): CompactFile {
  const canonical = loadCanonical();
  return {
    $generated: true,
    $schema_version: canonical.$schema_version,
    $warning: "GENERATED by scripts/build-compact.ts from data/compounds.json. Do not edit; the next build overwrites this file.",
    entries: canonical.entries.map(toCompact),
  };
}

if (process.argv[1] && process.argv[1].endsWith("build-compact.ts")) {
  const compact = buildCompact();
  mkdirSync(dirname(COMPACT_PATH), { recursive: true });
  writeFileSync(COMPACT_PATH, JSON.stringify(compact) + "\n");
  console.log(`wrote ${compact.entries.length} compact entries → data/generated/compounds.compact.json`);
}
