// Regenerated cross-reference index (BUILD_PLAN.md 0.9). Run: npm run build:index.
// Writes reports/03-index.md from data/compounds.json and data/chains.json,
// covering all four batches; replaces data/source/compound_readings_index.md
// (batches 1–3, hand-written, read-only history) as the maintained artifact.
// Every number is computed. No timestamp; byte-identical on unchanged inputs.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { ChainsFileSchema, type Chain, type Classification, type Entry } from "../src/data/schema";
import { CLASSIFICATION_LABELS, CLASSIFICATION_ORDER, PHONETIC_CHANGE_LABELS, PHONETIC_CHANGE_ORDER, READING_TYPE_LABELS } from "../src/data/labels";
import { loadCanonical } from "./build-compact";

const ROOT = process.cwd();
const CHAINS = join(ROOT, "data", "chains.json");
export const INDEX_PATH = join(ROOT, "reports", "03-index.md");

const md = (s: unknown) => String(s ?? "").replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
const cl = (c: Classification) => CLASSIFICATION_LABELS[c];

export function buildIndex(): string {
  const { entries } = loadCanonical();
  const chainsParsed = ChainsFileSchema.safeParse(JSON.parse(readFileSync(CHAINS, "utf8")));
  if (!chainsParsed.success) throw new Error("data/chains.json does not conform to the schema");
  const chains = [...chainsParsed.data.chains].sort((a, b) => a.display_order - b.display_order);
  const byId = new Map(entries.map((e) => [e.id, e]));
  const total = entries.length;
  const batches = [1, 2, 3, 4];

  const L: string[] = [];
  const P = (s = "") => L.push(s);
  const row = (e: Entry) => `| \`${e.id}\` | ${e.compound} | ${e.reading} | ${cl(e.classification)} | ${e.difficulty} | ${e.source_batch} |`;
  const header = () => {
    P("| ID | Compound | Reading | Classification | Difficulty | Batch |");
    P("|---|---|---|---|---|---|");
  };

  P("# 03-index.md — Cross-reference index of the canonical dataset");
  P();
  P(`Generated by \`scripts/build-index.ts\` (\`npm run build:index\`) from \`data/compounds.json\` and \`data/chains.json\`. Covers all four batches (${total} entries). Every number is computed; the file is regenerated on every build. It replaces \`data/source/compound_readings_index.md\`, which covers batches 1–3 only and is kept as read-only history.`);
  P();

  P("## 1. Entries by classification");
  P();
  P("| Classification | " + batches.map((b) => `Batch ${b}`).join(" | ") + " | Total |");
  P("|---|" + batches.map(() => "---|").join("") + "---|");
  for (const c of CLASSIFICATION_ORDER)
    P(`| ${cl(c)} | ${batches.map((b) => entries.filter((e) => e.source_batch === b && e.classification === c).length).join(" | ")} | ${entries.filter((e) => e.classification === c).length} |`);
  P(`| **Total** | ${batches.map((b) => `**${entries.filter((e) => e.source_batch === b).length}**`).join(" | ")} | **${total}** |`);
  P();
  const ju = entries.filter((e) => e.classification === "juubako").length;
  const oo = entries.filter((e) => e.classification === "on_on").length;
  P(`重箱 is ${ju} of ${total} entries; 音音 has ${(oo / ju).toFixed(2)}× as many (${oo}). This reflects how the dataset was built, not Japanese frequency (CLAUDE.md §5).`);
  P();
  for (const c of CLASSIFICATION_ORDER) {
    const xs = entries.filter((e) => e.classification === c);
    P(`### ${cl(c)} (${xs.length})`);
    P();
    header();
    for (const e of xs) P(row(e));
    P();
  }

  P("## 2. Entries by difficulty");
  P();
  P("| Difficulty | Entries | " + CLASSIFICATION_ORDER.map(cl).join(" | ") + " |");
  P("|---|---|" + CLASSIFICATION_ORDER.map(() => "---|").join(""));
  for (const d of [1, 2, 3, 4]) {
    const xs = entries.filter((e) => e.difficulty === d);
    P(`| ${d} | ${xs.length} | ${CLASSIFICATION_ORDER.map((c) => xs.filter((e) => e.classification === c).length).join(" | ")} |`);
  }
  P();
  for (const d of [1, 2, 3, 4]) {
    const xs = entries.filter((e) => e.difficulty === d);
    P(`### Difficulty ${d} (${xs.length})`);
    P();
    P(xs.map((e) => `${e.compound} (${cl(e.classification)})`).join(", "));
    P();
  }

  P("## 3. Entries by phonetic change");
  P();
  P("| Code | Display | Entries |");
  P("|---|---|---|");
  for (const p of PHONETIC_CHANGE_ORDER) P(`| \`${p}\` | ${PHONETIC_CHANGE_LABELS[p]} | ${entries.filter((e) => e.phonetic_changes.includes(p)).length} |`);
  P(`| — | none | ${entries.filter((e) => e.phonetic_changes.length === 0).length} |`);
  P();
  for (const p of PHONETIC_CHANGE_ORDER) {
    const xs = entries.filter((e) => e.phonetic_changes.includes(p));
    if (!xs.length) continue;
    P(`### ${PHONETIC_CHANGE_LABELS[p]} \`${p}\` (${xs.length})`);
    P();
    P("| ID | Compound | Reading | Classification | Detail |");
    P("|---|---|---|---|---|");
    for (const e of xs) P(`| \`${e.id}\` | ${e.compound} | ${e.reading} | ${cl(e.classification)} | ${md(e.phonetic_change_detail)} |`);
    P();
  }

  P(`## 4. Chains (${chains.length}, \`data/chains.json\` \`$status: "${chainsParsed.data.$status}"\`)`);
  P();
  P("| # | Chain | Reliability | Entries | Classifications spanned | Rule |");
  P("|---|---|---|---|---|---|");
  const members = (c: Chain) => c.entry_order.map((id) => byId.get(id)).filter((e): e is Entry => !!e);
  for (const c of chains) {
    const xs = members(c);
    P(`| ${c.display_order} | ${c.character} | ${c.rule_reliability} | ${xs.length} | ${new Set(xs.map((e) => e.classification)).size} | ${md(c.rule ?? "—")} |`);
  }
  P();
  for (const c of chains) {
    const xs = members(c);
    P(`### ${c.character} (${xs.length} entries, rule_reliability \`${c.rule_reliability}\`)`);
    P();
    if (c.rule) P(`**Rule:** ${c.rule}`);
    if (c.teaching_note) P(`**Teaching note:** ${c.teaching_note}`);
    if (c.rule || c.teaching_note) P();
    if (!xs.length) {
      P("(no entries)");
      P();
      continue;
    }
    P(`| Compound | Reading | ${c.character} reading | Type | Classification |`);
    P("|---|---|---|---|---|");
    for (const e of xs) {
      const ch = e.characters.find((x) => x.kanji === c.character);
      P(`| ${e.compound} | ${e.reading} | ${ch?.reading_in_compound ?? "—"} | ${ch ? READING_TYPE_LABELS[ch.reading_type] : "—"} | ${cl(e.classification)} |`);
    }
    P();
  }
  const zero = entries.filter((e) => e.chains.length === 0);
  P(`Entries in no chain: ${zero.length} — ${zero.map((e) => e.compound).join(", ")}.`);
  P();

  const contested = entries.filter((e) => e.contested);
  P(`## 5. Contested readings (${contested.length})`);
  P();
  P("| ID | Compound | Primary | Alternates (status) | Note |");
  P("|---|---|---|---|---|");
  for (const e of contested) P(`| \`${e.id}\` | ${e.compound} | ${e.reading} | ${e.alternate_readings.map((a) => `${a.reading} (\`${a.status}\`)`).join(", ") || "none recorded"} | ${md(e.contested_note)} |`);
  P();

  const withAlt = entries.filter((e) => e.alternate_readings.length);
  P(`## 6. Entries with alternate readings (${withAlt.length})`);
  P();
  P("| ID | Compound | Primary (classification) | Alternates |");
  P("|---|---|---|---|");
  for (const e of withAlt) P(`| \`${e.id}\` | ${e.compound} | ${e.reading} (${cl(e.classification)}) | ${e.alternate_readings.map((a) => `${a.reading} (${cl(a.classification)}, \`${a.status}\`)`).join("; ")} |`);
  P();

  const tagValues = [...new Set(entries.flatMap((e) => e.tags))].sort();
  P(`## 7. Tags (${tagValues.length} values)`);
  P();
  P("| Tag | Entries |");
  P("|---|---|");
  for (const t of tagValues) P(`| \`${t}\` | ${entries.filter((e) => e.tags.includes(t)).map((e) => e.compound).join(", ")} |`);
  P();

  const kana = entries.filter((e) => e.has_kana);
  P("## 8. Structure");
  P();
  P(`- Character counts: ${[1, 2, 3].map((n) => `${n} kanji × ${entries.filter((e) => e.char_count === n).length}`).join(", ")}`);
  P(`- Compounds containing kana (\`has_kana\`): ${kana.length} — ${kana.map((e) => e.compound).join(", ")}`);
  P(`- Non-decomposable (熟字訓): ${entries.filter((e) => !e.decomposable).length}`);
  P(`- With trap notes: ${entries.filter((e) => e.trap_note).length}; without: ${entries.filter((e) => !e.trap_note).length}`);
  P();

  return L.join("\n") + "\n";
}

if (process.argv[1] && process.argv[1].endsWith("build-index.ts")) {
  writeFileSync(INDEX_PATH, buildIndex());
  console.log("wrote reports/03-index.md");
}
